### ISSUE TITLE
CH10 美食分享範例Code無法順利執行( bcrypt 0.8.7 在win10上的問題 )

### ISSUE THREAD

**Issue by Crygar** [kdchang/reactjs101#37]
您好，首先感謝您編輯了這麼一本好書，著實獲益良多。以下是我的問題：

　　我在執行ch10美食分享範例時，由於win10環境下執行npm install指令會有其中一項[bcrypt 0.8.7無法安裝](https://github.com/kelektiv/node.bcrypt.js/issues/442)，即使照著[nodejs/node-gyp的操作](https://github.com/nodejs/node-gyp#installation)，依然無法解決問題。

> On Windows:
> Option 2: 
--Install Visual Studio 2015 (or modify an existing installation) and select Common Tools for　Visual C++ during setup. This also works with the free Community and Express for Desktop editions.
　　💡 [Windows Vista / 7 only] requires .NET Framework 4.5.1

> --Install Python 2.7 (v3.x.x is not supported), and run npm config set python python2.7 (or see below for further instructions on specifying the proper Python version and path.)

> --Launch cmd, npm config set msvs_version 2015

　　由於一直無法解決bcrypt 0.8.7安裝問題索性尋找[bcryptjs作為替代方案](http://npm.taobao.org/package/bcryptjs)，在package.json刪除bcrypt 0.8.7並手動npm install bcryptjs後直接npm start，一樣沒解決問題，顯示訊息與bcrypt 0.8.7沒安裝完成時執行npm start的情況一模一樣。
　　
　　請問我是不是漏了什麼步驟，亦或是我沒有找到對的解決方法，以至於導致範例code無法順利運行的情況呢？

```
==> �  Listening on port 3000. Open up http://localhost:3000/ in your browser.

C:\Users\user\Documents\ReactJS\react-router-redux-node-isomorphic-open-cook\node_modules\mongodb\lib\server.js:261
        process.nextTick(function() { throw err; })
                                      ^
MongoError: failed to connect to server [localhost:27017] on first connect
    at Pool.<anonymous> (C:\Users\user\Documents\ReactJS\react-router-redux-node-isomorphic-open-cook\node_modules\mongodb-core\lib\topologies\server.js:313:35)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:188:7)
    at Connection.<anonymous> (C:\Users\user\Documents\ReactJS\react-router-redux-node-isomorphic-open-cook\node_modules\mongodb-core\lib\connection\pool.js:260:12)
    at Connection.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (C:\Users\user\Documents\ReactJS\react-router-redux-node-isomorphic-open-cook\node_modules\mongodb-core\lib\connection\connection.js:162:49)
    at Socket.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1271:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by kdchang** [comment]
@Crygar 您好，謝謝您的肯定，請問您的問題解決了嗎？

**Comment by Crygar** [comment]
@kdchang 您好，很抱歉這麼晚才回應。

　　我後來額外在系統上裝了MongoDB 3.2.10後，cmd -> mongod後可以監聽localhost:3000了，但DB無法連到localhost（shut down後mongod.lock有清空），所以初始化的資料跟預設的帳號密碼都沒有寫進去，只看得到一個view。

P.S bcrypt 0.8.7的問題我改用install bcryptjs解決。

![ch10_example_problem3](https://cloud.githubusercontent.com/assets/17195992/19624008/c2bc2e20-9915-11e6-82f2-4137d317c030.JPG)
![ch10_example_problem4](https://cloud.githubusercontent.com/assets/17195992/19624009/c5df05be-9915-11e6-8157-034102c78bd9.JPG)
![ch10_example_problem1](https://cloud.githubusercontent.com/assets/17195992/19624010/c86275a0-9915-11e6-83e2-dd68259232e8.JPG)
![ch10_example_problem2](https://cloud.githubusercontent.com/assets/17195992/19624011/cb1ab244-9915-11e6-833a-d4680563932c.JPG)

**Comment by chienfuchen32** [comment]
謝謝你的幫助! 我也是使用bcryptjs才跳過windows編譯的錯誤

**Comment by Crygar** [comment]
@chienfuchen32 很高興自己的經驗能對別人有所幫助 ：）

**Comment by chienfuchen32** [comment]
@Crygar 你好 我目前是使用Mongoose官方範例 於MongoDB建製作者的user collection才看的到完整的網站功能
